export default [
  { en: 'Genesis', vi: 'Sáng-thế ký' },
  { en: 'Exodus', vi: 'Xuất Ê-dip-tô Ký' },
  { en: 'Leviticus', vi: 'Lê-vi Ký' },
  { en: 'Numbers', vi: 'Dân-số Ký' },
  { en: 'Deuteronomy', vi: 'Phục-truyền Luật-lệ Ký' },
  { en: 'Joshua', vi: 'Giô-suê' },
  { en: 'Judges', vi: 'Các Quan Xét' },
  { en: 'Ruth', vi: 'Ru-tơ' },
  { en: '1 Samuel', vi: '2 Sa-mu-ên' },
  { en: '2 Samuel', vi: '2 Sa-mu-ên' },
  { en: '1 Kings', vi: '1 Các Vua' },
  { en: '2 Kings', vi: '2 Các Vua' },
  { en: '1 Chronicles', vi: '1 Sử-ký' },
  { en: '2 Chronicles', vi: '2 Sử-ký' },
  { en: 'Ezra', vi: 'E-xơ-ra' },
  { en: 'Nehemiah', vi: 'Nê-hê-mi' },
  { en: 'Esther', vi: 'Ê-xơ-tê' },
  { en: 'Job', vi: 'Gióp' },
  { en: 'Psalm', vi: 'Thi-thiên' },
  { en: 'Proverbs', vi: 'Châm-ngôn' },
  { en: 'Ecclesiastes', vi: 'Truyền-đạo' },
  { en: 'Song of Songs', vi: 'Nhã-ca' },
  { en: 'Isaiah', vi: 'Ê-sai' },
  { en: 'Jeremiah', vi: 'Giê-rê-mi' },
  { en: 'Lamentations', vi: 'Ca thương' },
  { en: 'Ezekiel', vi: 'Ê-xê-chi-ên' },
  { en: 'Daniel', vi: 'Đa-ni-ên' },
  { en: 'Hosea', vi: 'Ô-sê' },
  { en: 'Joel', vi: 'Giô-ên' },
  { en: 'Amos', vi: 'A-mốt' },
  { en: 'Obadiah', vi: 'Áp-đia' },
  { en: 'Jonah', vi: 'Giô-na' },
  { en: 'Micah', vi: 'Mi-chê' },
  { en: 'Nahum', vi: 'Na-hum' },
  { en: 'Hab.', vi: 'Ha-ba-cúc' },
  { en: 'Zephaniah', vi: 'Sô-phô-ni' },
  { en: 'Haggai', vi: 'A-ghê' },
  { en: 'Zechariah', vi: 'Xa-cha-ri' },
  { en: 'Malachi', vi: 'Ma-la-chi' },
  { en: 'Matthew', vi: 'Ma-thi-ơ' },
  { en: 'Mark', vi: 'Mác' },
  { en: 'Luke', vi: 'Lu-ca' },
  { en: 'John', vi: 'Giăng' },
  { en: 'Acts', vi: 'Công-vụ' },
  { en: 'Romans', vi: 'Rô-ma' },
  { en: '1 Corinthians', vi: '1 Cô-rinh-tô' },
  { en: '2 Corinthians', vi: '2 Cô-rinh-tô' },
  { en: 'Galatians', vi: 'Ga-la-ti' },
  { en: 'Ephesians', vi: 'Ê-phê-sô' },
  { en: 'Philippians', vi: 'Phi-líp' },
  { en: 'Colossians', vi: 'Cô-lô-se' },
  { en: '1 Thessalonians', vi: '1 Tê-sa-lô-ni-ca' },
  { en: '2 Thessalonians', vi: '2 Tê-sa-lô-ni-ca' },
  { en: '1 Timothy', vi: '1 Ti-mô-thê' },
  { en: '2 Timothy', vi: '2 Ti-mô-thê' },
  { en: 'Titus', vi: 'Tít' },
  { en: 'Philemon', vi: 'Phi-lê-môn' },
  { en: 'Hebrews', vi: 'Hê-bơ-rơ' },
  { en: 'James', vi: 'Gia-cơ' },
  { en: '1 Peter', vi: '1 Phi-e-rơ' },
  { en: '2 Peter', vi: '2 Phi-e-rơ' },
  { en: '1 John', vi: '1 Giăng' },
  { en: '2 John', vi: '2 Giăng' },
  { en: '3 John', vi: '3 Giăng' },
  { en: 'Jude', vi: 'Giu-đe' },
  { en: 'Revelation', vi: 'Khải-huyền' },
];
