'use strict';

module.exports = {
  gen: { en: 'Genesis', vi: 'Sáng-thế ký' },
  exo: { en: 'Exodus', vi: 'Xuất Ê-dip-tô Ký' },
  lev: { en: 'Leviticus', vi: 'Lê-vi Ký' },
  num: { en: 'Numbers', vi: 'Dân-số Ký' },
  deu: { en: 'Deuteronomy', vi: 'Phục-truyền Luật-lệ Ký' },
  jos: { en: 'Joshua', vi: 'Giô-suê' },
  jdg: { en: 'Judges', vi: 'Các Quan Xét' },
  rut: { en: 'Ruth', vi: 'Ru-tơ' },
  '1sa': { en: '1 Samuel', vi: '2 Sa-mu-ên' },
  '2sa': { en: '2 Samuel', vi: '2 Sa-mu-ên' },
  '1ki': { en: '1 Kings', vi: '1 Các Vua' },
  '2ki': { en: '2 Kings', vi: '2 Các Vua' },
  '1ch': { en: '1 Chronicles', vi: '1 Sử-ký' },
  '2ch': { en: '2 Chronicles', vi: '2 Sử-ký' },
  ezr: { en: 'Ezra', vi: 'E-xơ-ra' },
  neh: { en: 'Nehemiah', vi: 'Nê-hê-mi' },
  est: { en: 'Esther', vi: 'Ê-xơ-tê' },
  job: { en: 'Job', vi: 'Gióp' },
  psa: { en: 'Psalm', vi: 'Thi-thiên' },
  pro: { en: 'Proverbs', vi: 'Châm-ngôn' },
  ecc: { en: 'Ecclesiastes', vi: 'Truyền-đạo' },
  sng: { en: 'Song of Songs', vi: 'Nhã-ca' },
  isa: { en: 'Isaiah', vi: 'Ê-sai' },
  jer: { en: 'Jeremiah', vi: 'Giê-rê-mi' },
  lam: { en: 'Lamentations', vi: 'Ca thương' },
  ezk: { en: 'Ezekiel', vi: 'Ê-xê-chi-ên' },
  dan: { en: 'Daniel', vi: 'Đa-ni-ên' },
  hos: { en: 'Hosea', vi: 'Ô-sê' },
  jol: { en: 'Joel', vi: 'Giô-ên' },
  amo: { en: 'Amos', vi: 'A-mốt' },
  oba: { en: 'Obadiah', vi: 'Áp-đia' },
  jon: { en: 'Jonah', vi: 'Giô-na' },
  mic: { en: 'Micah', vi: 'Mi-chê' },
  nam: { en: 'Nahum', vi: 'Na-hum' },
  hab: { en: 'Hab.', vi: 'Ha-ba-cúc' },
  zep: { en: 'Zephaniah', vi: 'Sô-phô-ni' },
  hag: { en: 'Haggai', vi: 'A-ghê' },
  zec: { en: 'Zechariah', vi: 'Xa-cha-ri' },
  mal: { en: 'Malachi', vi: 'Ma-la-chi' },
  mat: { en: 'Matthew', vi: 'Ma-thi-ơ' },
  mrk: { en: 'Mark', vi: 'Mác' },
  luk: { en: 'Luke', vi: 'Lu-ca' },
  jnh: { en: 'John', vi: 'Giăng' },
  act: { en: 'Acts', vi: 'Công-vụ' },
  rom: { en: 'Romans', vi: 'Rô-ma' },
  '1co': { en: '1 Corinthians', vi: '1 Cô-rinh-tô' },
  '2co': { en: '2 Corinthians', vi: '2 Cô-rinh-tô' },
  gal: { en: 'Galatians', vi: 'Ga-la-ti' },
  eph: { en: 'Ephesians', vi: 'Ê-phê-sô' },
  php: { en: 'Philippians', vi: 'Phi-líp' },
  col: { en: 'Colossians', vi: 'Cô-lô-se' },
  '1th': { en: '1 Thessalonians', vi: '1 Tê-sa-lô-ni-ca' },
  '2th': { en: '2 Thessalonians', vi: '2 Tê-sa-lô-ni-ca' },
  '1ti': { en: '1 Timothy', vi: '1 Ti-mô-thê' },
  '2ti': { en: '2 Timothy', vi: '2 Ti-mô-thê' },
  tit: { en: 'Titus', vi: 'Tít' },
  phm: { en: 'Philemon', vi: 'Phi-lê-môn' },
  heb: { en: 'Hebrews', vi: 'Hê-bơ-rơ' },
  jas: { en: 'James', vi: 'Gia-cơ' },
  '1pe': { en: '1 Peter', vi: '1 Phi-e-rơ' },
  '2pe': { en: '2 Peter', vi: '2 Phi-e-rơ' },
  '1jn': { en: '1 John', vi: '1 Giăng' },
  '2jn': { en: '2 John', vi: '2 Giăng' },
  '3jn': { en: '3 John', vi: '3 Giăng' },
  jud: { en: 'Jude', vi: 'Giu-đe' },
  rev: { en: 'Revelation', vi: 'Khải-huyền' }
}